kind: Service
apiVersion: v1
metadata:
  name: revproxy-service
spec:
  selector:
    app: revproxy
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: http
  type: NodePort
