apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "revproxy-service-alb-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:082619190404:certificate/4e6e4243-d596-4744-a8b2-736248ee46e9
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
  labels:
    app: revproxy
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "revproxy-service-alb"
              servicePort: 443